/**
 * Todo (development)
 * API for the TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HealthCheckStatus } from './healthCheckStatus';


export interface HealthCheckResponse { 
    data?: object | null;
    name?: string;
    status?: HealthCheckStatus;
}
export namespace HealthCheckResponse {
}


