/**
 * Todo (development)
 * API for the TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TodoV1 } from './todoV1';


export interface PaginationResponseV1TodoV1 { 
    data?: Array<TodoV1>;
    pageIndex?: number;
    pageSize?: number;
    totalPages?: number;
    totalItems?: number;
}

