/**
 * Todo (development)
 * API for the TODO
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriorityV1 } from './priorityV1';


export interface TodoV1 { 
    id?: number;
    title?: string;
    completed?: boolean;
    priority?: PriorityV1;
}

